name: CI

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 2 * * *"  # nightly tests

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements/ci.txt
      - name: Code style & security
        run: |
          black .
          isort .
          bandit -r autoshift_core -ll
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements/test.txt
      - run: pytest --cov=src 
      - uses: codecov/codecov-action@v4
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      contents: read
    needs: test
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ github.sha }}" > VERSION
      - name: Build & push image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
